name: pci_env
channels:
  - plotly
  - anaconda
  - defaults
dependencies:
  - keras-gpu=2.2.0
  - numpy=1.14.5
  - pandas=0.23.1
  - plotly=3.4.1  
  - python=3.6.6
  - pytest=3.9.1
  - scikit-learn=0.19.1
  - sqlite=3.26.0
  - tensorflow-gpu=1.8.0
  - pip:
    - jieba-fast==0.53
    - MonthDelta==0.9.1
